export { default as Package } from '#routers/settings/PackageRoute'
export { default as GuidanceType } from '#routers/settings/GuidanceTypeRoute'
export { default as SchoolYear } from '#routers/settings/SchoolYearRoute'
export { default as Session } from '#routers/settings/SessionRoute'
export { default as Setting } from '#routers/settings/SettingRoute'